### ISSUE TITLE
Implement networking between nodes using Protobuf

### ISSUE THREAD

**Issue by optmzr** [optmzr/camomile#20]
Marshal/unmarshal a Protobuf message between two nodes.

**Comment by optmzr** [comment]
Blocks #21

**Comment by edvinnn** [comment]
Currently blocked by Kademlia not yet implemented

**Comment by optmzr** [comment]
Shiiiiiiiiiiiet

**Comment by optmzr** [comment]
This is kind of what you're doing now @edvinnn, I'll rename the issue.
