### ISSUE TITLE
Connect republish/replication channel to dht

### ISSUE THREAD

**Issue by Hjortsberg** [optmzr/camomile#59]

**Comment by optmzr** [comment]
I just noticed that this method:
https://github.com/optmzr/camomile/blob/master/dht/dht.go#L182

is missing the `dht.db.AddLocalItem(hash, value)` call.

**Comment by edvinnn** [comment]
> I just noticed that this method:
> https://github.com/optmzr/camomile/blob/master/dht/dht.go#L182
> 
> is missing the `dht.db.AddLocalItem(hash, value)` call.

Actually I don't get it. Isn't everything right here?

**Comment by optmzr** [comment]
Sorry, I pasted a bad link, I meant this method: 

https://github.com/optmzr/camomile/blob/7d6a17d5d8685ae71849f2a6acc72a93eec36916/dht/dht.go#L193
