### ISSUE TITLE
M2: Object distribution

### ISSUE THREAD

**Issue by optmzr** [optmzr/camomile#6]
![2019-09-03-185250_678x159_scrot](https://user-images.githubusercontent.com/4541181/64192915-08c67080-ce7c-11e9-889e-da313f435e7a.png)

**Comment by Hjortsberg** [comment]
> ![2019-09-03-185250_678x159_scrot](https://user-images.githubusercontent.com/4541181/64192915-08c67080-ce7c-11e9-889e-da313f435e7a.png)

This one is considered complete, am I right?

> ![2019-09-03-185836_709x218_scrot](https://user-images.githubusercontent.com/4541181/64193329-d701d980-ce7c-11e9-892b-6166ad740c3d.png)

I see that I've missed to refresh the TTL when a value is requested. Will add ticket.

> ![2019-09-03-190152_689x65_scrot](https://user-images.githubusercontent.com/4541181/64193569-51caf480-ce7d-11e9-9750-1fa09f0a9932.png)

And this is considered done? We can account for thread safety due to the use of Mutexes.

**Comment by optmzr** [comment]
![2019-10-12-182423_614x99_scrot](https://user-images.githubusercontent.com/4541181/66704592-9ae45300-ed1d-11e9-9615-8e35019ffe8f.png)

Okay, so now this one is the only one left. :hammer:

**Comment by Hjortsberg** [comment]
The last one is fixed since #79. Closing
