### ISSUE TITLE
Limit number of maximum nodes to store at to k

### ISSUE THREAD

**Issue by optmzr** [optmzr/camomile#61]

**Comment by optmzr** [comment]
I'm confused about this one. Didn't I fix this in c8e04115fa3ec1ddd117eb35e071cae772a82b22?

Maybe I was thinking about the number of nodes to do a look up from? ... Eh...

**Comment by Hjortsberg** [comment]
Eh, thats a good question. It seems we need to try this out to see if it works

**Comment by optmzr** [comment]
Let's close this and just pretend this issue was never opened.
