### ISSUE TITLE
Replication events are for the whole database

### ISSUE THREAD

**Issue by optmzr** [optmzr/camomile#62]
It seems that the `republishHandler` in `store` only iterates over the local items (`db.localItems`), but according to:

![2019-10-04-100753_893x41_scrot](https://user-images.githubusercontent.com/4541181/66191523-d7b1a980-e68e-11e9-8184-c574680f6e5e.png)

The _whole_ database must be replicated every hour?

Ping @Hjortsberg

**Comment by Hjortsberg** [comment]
Correct,  replication should only work on items stored on the node according to what I've read. I.E the entire stored database.

**Comment by Hjortsberg** [comment]
I had done a oopsie. This is in progress as well as race fix

**Comment by Hjortsberg** [comment]
Fixed in #64
