### ISSUE TITLE
Refresh tExpire when a value is requested

### ISSUE THREAD

**Issue by Hjortsberg** [optmzr/camomile#78]

**Comment by optmzr** [comment]
Åh fan

**Comment by optmzr** [comment]
Doesn't this happen automagically tho? As the items are overwritten if they have the same key?

**Comment by optmzr** [comment]
Oh. _Requested_. Never mind 🙃

**Comment by Hjortsberg** [comment]
> Oh. _Requested_. Never mind upside_down_face

I think we're all a little mushy in the head today :smile:

**Comment by Hjortsberg** [comment]
fixed: #79
